name: Release

on:
  push:
    tags:
      - 'v*'
      
jobs:
  build:
    name: Build and create zipped release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      
      - name: Install cross
        run: cargo install cross
      
      - name: Build binary
        run: cross build --release --target aarch64-unknown-linux-musl
      
      - name: Zip binary
        run: |
          cd target/aarch64-unknown-linux-musl/release/
          zip pipinrs-${{ github.ref_name }}.zip pipinrs
          cd ../../../
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/aarch64-unknown-linux-musl/release/pipinrs-${{ github.ref_name }}.zip
          generate_release_notes: true
